[Interface]
PrivateKey = qFDmdw3R2mp64nPoKunGVoT5vsyxLR3hmq00Y7hvZ3g=
Address = 10.11.0.2/24
ListenPort = 51821

[Peer]
PublicKey = 6I4k1GZj4w5hlMn9G+dQGBcdQ5jG9IEzohDTVjVbQR8=
Endpoint = 192.168.100.1:51820
AllowedIPs = 10.11.0.1/32
PersistentKeepalive = 25
