[Interface]
PrivateKey = +JapmNpgOFb/Gvl6mkVecICW+N+NjOBFqhTDQ2w5P2U=
Address = 10.11.0.1/24
ListenPort = 51820

[Peer]
PublicKey = 83M+Pgzv6orG40gxuv6HcsLA93JdJa9q6SM/z6pnXh4=
AllowedIPs = 10.11.0.2/32
